# Generated by Django 5.2.14 on 2026-06-26 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberClosureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(db_index=True, max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('dry_run', models.BooleanField(default=False)),
                ('panaccess_result', models.JSONField(blank=True, null=True)),
                ('local_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='listofsubscriber',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listofsubscriber',
            name='closed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listofsubscriber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending_closure', 'Pending closure')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriberdocumentregistry',
            name='account_closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberdocumentregistry',
            name='closed_subscriber_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriberdocumentregistry',
            name='eligible_for_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriberdocumentregistry',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberdocumentregistry',
            name='trial_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberdocumentregistry',
            name='trial_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subscriberemailregistry',
            name='account_closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberemailregistry',
            name='closed_subscriber_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriberemailregistry',
            name='eligible_for_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriberemailregistry',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberemailregistry',
            name='trial_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriberemailregistry',
            name='trial_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='subscriberdocumentregistry',
            index=models.Index(fields=['trial_used'], name='wind_subscr_trial_u_fca576_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberdocumentregistry',
            index=models.Index(fields=['account_closed_at'], name='wind_subscr_account_771ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberemailregistry',
            index=models.Index(fields=['trial_used'], name='wind_subscr_trial_u_77fb03_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriberemailregistry',
            index=models.Index(fields=['account_closed_at'], name='wind_subscr_account_b8eb99_idx'),
        ),
        migrations.AddField(
            model_name='subscriberclosurelog',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber_closures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscriberclosurelog',
            index=models.Index(fields=['subscriber_code', 'created_at'], name='wind_subscr_subscri_39c786_idx'),
        ),
    ]
