# Generated by Django 5.2.14 on 2026-07-21 14:16
# Editado a mano para sumar el AlterField de EncryptedCredentialsLog.app_credentials
# (pasa a nullable/SET_NULL -- ver models.py) tras regenerar el resto con
# makemigrations en el mismo entorno de auditoría de siempre (sin acceso a
# Postgres real).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0006_rename_app_credentials_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='udidauthrequest',
            name='device_public_key',
            field=models.TextField(blank=True, help_text='Llave pública RSA (PEM) generada por el dispositivo para este pareo específico.', null=True),
        ),
        migrations.AlterField(
            model_name='appcredentials',
            name='app_type',
            field=models.CharField(choices=[('web', 'Web'), ('lg', 'LG webOS TV'), ('samsung', 'Samsung Tizen TV'), ('android', 'Android'), ('androidtv', 'Android TV'), ('amazon', 'Amazon Fire TV'), ('iOS', 'iOS'), ('iOStv', 'iOS TV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='authauditlog',
            name='action_type',
            field=models.CharField(choices=[('udid_generated', 'UDID Generated'), ('udid_validated', 'UDID Validated'), ('udid_used', 'UDID Used'), ('udid_revoked', 'UDID Revoked'), ('login_attempt', 'Login Attempt'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='encryptedcredentialslog',
            name='app_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wind.appcredentials'),
        ),
    ]
