# Generated by Django 5.2.14 on 2026-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0007_udidauthrequest_device_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subscriber_code', models.CharField(db_index=True, max_length=100)),
                ('device_type', models.CharField(blank=True, choices=[('web', 'Web'), ('lg', 'LG webOS TV'), ('samsung', 'Samsung Tizen TV'), ('android', 'Android'), ('androidtv', 'Android TV'), ('amazon', 'Amazon Fire TV'), ('iOS', 'iOS'), ('iOStv', 'iOS TV')], max_length=50, null=True)),
                ('device_model', models.CharField(blank=True, help_text="Texto libre reportado por el cliente, p.ej. 'Samsung QN90A' o 'Chrome en Windows'.", max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['subscriber_code', 'status'], name='wind_device_subscri_9d0d4c_idx'), models.Index(fields=['device_token'], name='wind_device_device__01b52f_idx')],
            },
        ),
    ]
