# Generated by Django 5.2.14 on 2026-08-26 18:01
#
# Completa lo que dejó pendiente 0004_db_performance_indexes.py: ese
# migration agregó un índice funcional Upper(emails) en ListOfSubscriber,
# pero el camino de login (resolve_subscriber_code() / find_login_record(),
# wind/services/subscriber_auth.py) también filtra code__iexact,
# email__iexact (SubscriberEmailRegistry) y login2__iexact
# (SubscriberLoginInfo) -- ninguno de los tres tenía índice funcional, así
# que cada uno hacía sequential scan en cada intento de login. Ver hallazgo
# Alto #5 y docs/OPTIMIZACION_LATENCIA_LOGIN_2026-08-26.md (demora
# reportada de 10-15 segundos en login).

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0008_devicesession'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listofsubscriber',
            index=models.Index(django.db.models.functions.text.Upper('code'), name='wind_lof_sub_code_upper'),
        ),
        migrations.AddIndex(
            model_name='subscriberemailregistry',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='wind_ser_email_upper'),
        ),
        migrations.AddIndex(
            model_name='subscriberlogininfo',
            index=models.Index(django.db.models.functions.text.Upper('login2'), name='wind_sli_login2_upper'),
        ),
    ]
