# Generated by Django 5.2.14 on 2026-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0009_login_functional_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(db_index=True, max_length=100)),
                ('profile_key', models.CharField(default='default', max_length=100)),
                ('parental', models.JSONField(blank=True, null=True)),
                ('favorite_channel_ids', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['subscriber_code', 'profile_key'], name='wind_subscr_subscri_198aa6_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscriber_code', 'profile_key'), name='unique_subscriber_profile_preferences')],
            },
        ),
    ]
