# Generated by Django 5.2.14 on 2026-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0010_subscriber_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcredentials',
            name='supports_aead',
            field=models.BooleanField(default=False),
        ),
    ]
