# Generated by hand (2026-09-14) -- entorno de este sandbox no tiene acceso
# a `manage.py makemigrations` en esta sesión (ver docs/CAMBIO_CONTRASENA_OTP_2026-09-14.md,
# sección de verificación). Estructura sigue el mismo patrón que
# 0012_scheduled_account_deletion.py. El índice usa nombre explícito
# ("wind_pwd_otp_lookup_idx", ver Meta.indexes en wind/models.py) para no
# depender del hash auto-generado por Django -- si más adelante se corre
# `manage.py makemigrations` en un entorno con acceso completo, debería
# detectar el estado como ya sincronizado (sin diffs pendientes).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0012_scheduled_account_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(db_index=True, max_length=100)),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['subscriber_code', 'consumed_at', 'expires_at'],
                        name='wind_pwd_otp_lookup_idx',
                    ),
                ],
            },
        ),
    ]
