# Generated by Django 5.2.14 on 2026-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind', '0013_passwordchangeotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberdocumentregistry',
            name='subscriber_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriberemailregistry',
            name='subscriber_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
