# Generated by Django 5.2.14 on 2026-08-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryIngestCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='ott', max_length=50, unique=True)),
                ('last_record_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telemetry_ingest_cursor',
            },
        ),
        migrations.CreateModel(
            name='TelemetryOttChannelName',
            fields=[
                ('channel_id', models.PositiveIntegerField(help_text='dataId de PanAccess -- identificador numérico del canal.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telemetry_ott_channel_name',
            },
        ),
        migrations.CreateModel(
            name='TelemetryChannelDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('channel_id', models.PositiveIntegerField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_subscribers', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'telemetry_channel_daily_agg',
                'indexes': [models.Index(fields=['day', 'channel_id'], name='telemetry_c_day_7c7345_idx'), models.Index(fields=['channel_id', 'day'], name='telemetry_c_channel_3112f7_idx')],
                'unique_together': {('day', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryOttViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.BigIntegerField(help_text='recordId de PanAccess -- único, permite ingesta idempotente (ignore_conflicts).', unique=True)),
                ('channel_id', models.PositiveIntegerField(db_index=True)),
                ('subscriber_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('smartcard_id', models.CharField(blank=True, max_length=50, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('event_date', models.DateField(db_index=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetry_ott_view_event',
                'indexes': [models.Index(fields=['event_date', 'channel_id'], name='telemetry_o_event_d_fb4ec7_idx'), models.Index(fields=['event_date', 'subscriber_code', 'channel_id'], name='telemetry_o_event_d_5d304d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryUserChannelDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('subscriber_code', models.CharField(db_index=True, max_length=50)),
                ('channel_id', models.PositiveIntegerField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'telemetry_user_channel_daily_agg',
                'indexes': [models.Index(fields=['day', 'subscriber_code', 'channel_id'], name='telemetry_u_day_b242e1_idx'), models.Index(fields=['subscriber_code', 'channel_id', 'day'], name='telemetry_u_subscri_322e7e_idx')],
                'unique_together': {('day', 'subscriber_code', 'channel_id')},
            },
        ),
    ]
